-- Business Question #1: Which sellers perform best when considering revenue,
-- delivery speed, and customer satisfaction?
-- This query will evaluate seller performance using the three metrics:
-- 1. Total revenue generated by each seller,
-- 2. Average delivery time (from purchase to delivery)
-- 3. Average customer review score
-- These metrics will be calculated in separate CTEs, then combined to provide
-- a comprehensive view of seller performance.

-- Revenue CTE
with revenue as (
	select
		seller_id,
		sum(price) as total_revenue
	from order_items
	group by seller_id
)
select *
from revenue
order by total_revenue desc;
